broker_ip="34.123.208.229"
broker_port=1883
path_data_temperature="./../Data/Temperature.csv"
path_data_wiatr_sila="./../Data/WindS.csv"
path_data_wiatr_kierunek="./../Data/WindD.csv"
path_data_entrance="./../Data/Entrance.csv"
path_data_wilgotnosc="./../Data/Wilgotnosc.csv"
path_data_co2="./../Data/Co2.csv"
path_data_level="./../Data/Level.csv"
path_data_gate="./../Data/Gate.csv"
path_data_rfid="./../Data/RFID.csv"
path_data_entrance2="./../Data/Entrance2.csv"
path_data_stairs="./../Data/Stairs.csv"
path_data_light="./../Data/Light.csv"
topic_grzalka="grzalka"
dic={"on":"1","off":"0"}
topic ={ "harmonogram_new":"harmonogram_new",
        "light_salon":"light_salon",
        "heating_switch":"heating_switch",
        "grzalka":"grzalka",
        "temperatura":"temperatura",
       "sila_wiatru":"sila_wiatru",
       "kierunek_wiatru":"kierunek_wiatru",
       "wejście":"wejście",
       "wilgotnosc":"wilgotnosc",
       "pir_stairs_1":"pir_stairs_1",
       "co2":"co2",
       "gateway_rswitch":"gateway_rswitch"}